config/routes.rb
Rails.application.routes.draw do
  namespace :api do
  get 'items/create'
  end

  namespace :api do
  get 'lists/create'
  end

  get 'lists/show'

  devise_for :users
  
  resources :users, only: [:update,:show]

  resources :lists do
    resources :items, only: [:create,:destroy]
  end

  get 'about' =>'welcome#about'

    
  authenticated :user do
    root to: 'users#show', as: :authenticated_root
  end
  
  root to: 'welcome#index'

  namespace :api, defaults: { format: :json } do
     resources :users do
      resources :lists 
    end

    resources :lists, only: [] do
      resources :items, only: [:create,:destroy,:update]
    end

    resources :items, only: [:destroy]
  end

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items, dependent: :destroy   
  belongs_to :user

  scope :viewable, -> {where(user_id: current_user)}
  
  validates :user, presence: true
  validates :name, length: {minimum: 5}, presence: true
end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApiController 
  before_action :authenticated?

  
    
  def create
    user = User.find(params[:user_id])
    list=user.lists.build(list_params)
    list.user=user
    raise "not authorized" unless ListPolicy.new(@logged_user, list).create?
    if list.save
      render json: list.to_json
    else
      render json: {errors: list.errors.full_messages}, status: :unprocessable_entity
    end
  end

  def destroy
     begin
      list = List.find(params[:id])
      items=list.items
      list.destroy
    raise "not authorized" unless ListPolicy.new(@logged_user, list).destroy?
      render json: {}, status: :no_content
     rescue ActiveRecord::RecordNotFound
       render :json => {}, :status => :not_found
     end
   end

   def update
   list = List.find(params[:id])
   raise "not authorized" unless ListPolicy.new(@logged_user, list).update?
   if list.update(list_params)
     render json: list.to_json
   else
     render json: { errors: list.errors.full_messages }, status: :unprocessable_entity
   end
 end

  private

  def list_params
    params.require(:list).permit(:name,:description)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
   def new
    @list=List.new
   end

   def show
    @user=User.find(current_user)
    @list=List.find(params[:id])
    @items=@list.items
    @item =Item.new
   end

   def create
    @user=current_user
    @list= current_user.lists.build(list_params)
    @list.user=@user

    if @list.save
       flash[:notice] = "List was saved."
       redirect_to @list
     else
       flash[:error] = "There was an error saving the list. Please try again."
       render :new
     end
  end

  def edit
    @list = List.find(params[:id])
  end

def update
     @list= List.find(params[:id])
     if @list.update_attributes(list_params)
       flash[:notice] = "List was updated."
       redirect_to @list
     else
       flash[:error] = "There was an error saving the list. Please try again."
       render :edit
     end
   end

  def destroy
     @user = current_user
     @list = List.find(params[:id])
     @items=@list.items
     
    if @list.destroy
      flash[:notice] = "List was deleted."
      redirect_to @user
    else
      flash[:error] = "Item couldn't be deleted. Try again."
      redirect_to @list
    end
  end

   def list_params
      params.require(:list).permit(:name,:description)
    end
end

app/helpers/api/lists_helper.rb
module Api::ListsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for list do |f| %>
  <% if list.errors.any? %>
    <div class="alert alert-danger">
      <h4>There is <%= pluralize(list.errors.count, "error") %></h4>
      </ul>
        <%list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <%end%>
      </ul>
    </div>
    <%end%>
      <%= form_group_tag(list.errors[:name]) do %>
        <%=f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter list name" %>
      <%end%>
       <div class="form-group">
         <%= f.label :description  %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter list description" %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>

app/views/lists/_list.html.erb
<div class="media">
     <div class="media-body">
        <h4 class="media-heading">
            <%= link_to list.name, list %>
          </h4>
         <small>
        <%= list.description %>
         <span class="badge"><%= pluralize(list.items.count, 'item')%></span>
    </small>
  </div>
</div>

app/views/lists/edit.html.erb
<h1>Edit List</h1>
 
 <div class="row">
   <div class="col-md-8">
      <%= render partial: 'form', locals: { list: @list} %>
   </div>
 </div>

app/views/lists/new.html.erb
 <h1>New List</h1>
 
 <div class="row">
   <div class="col-md-8">
      <%= render partial: 'form', locals: { list: @list} %>
  </div>
 </div>

app/views/lists/show.html.erb
</br><p><%= link_to " Back to all Lists",root_path, class: 'glyphicon glyphicon-circle-arrow-left' %></p>
<div class="col-md-8">
<h2><%=@list.name%></h2>
<div class='js-items-count'><h4><%= pluralize(@list.items.count, 'item')%></h4></div> 
<p><%=@list.description%></p>
<h4><%= link_to "Edit Description", edit_list_path, class: 'btn btn-success' %>
<%= link_to "Delete List", @list, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %> </h4>

</br>
</br>
  <div class='js-items'>
    <%= render partial: 'items/item', collection: @items %>
   </div>

</br>

  <div class='new-item'>
   <%= render partial: 'items/form', locals: { list:@list, item: @item} %>
  </div>
   </div>